# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ORB_VIO/viorb_msg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import std_msgs.msg

class viorb_msg(genpy.Message):
  _md5sum = "22701a4895958bd1b68178837a5aa9f2"
  _type = "ORB_VIO/viorb_msg"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
geometry_msgs/Pose Tic
geometry_msgs/Quaternion Qwi
geometry_msgs/Point gw
std_msgs/Bool VINSInitFlag
std_msgs/Int8 TrackStatus

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

================================================================================
MSG: std_msgs/Bool
bool data
================================================================================
MSG: std_msgs/Int8
int8 data
"""
  __slots__ = ['header','Tic','Qwi','gw','VINSInitFlag','TrackStatus']
  _slot_types = ['std_msgs/Header','geometry_msgs/Pose','geometry_msgs/Quaternion','geometry_msgs/Point','std_msgs/Bool','std_msgs/Int8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,Tic,Qwi,gw,VINSInitFlag,TrackStatus

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(viorb_msg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Tic is None:
        self.Tic = geometry_msgs.msg.Pose()
      if self.Qwi is None:
        self.Qwi = geometry_msgs.msg.Quaternion()
      if self.gw is None:
        self.gw = geometry_msgs.msg.Point()
      if self.VINSInitFlag is None:
        self.VINSInitFlag = std_msgs.msg.Bool()
      if self.TrackStatus is None:
        self.TrackStatus = std_msgs.msg.Int8()
    else:
      self.header = std_msgs.msg.Header()
      self.Tic = geometry_msgs.msg.Pose()
      self.Qwi = geometry_msgs.msg.Quaternion()
      self.gw = geometry_msgs.msg.Point()
      self.VINSInitFlag = std_msgs.msg.Bool()
      self.TrackStatus = std_msgs.msg.Int8()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_14dBb.pack(_x.Tic.position.x, _x.Tic.position.y, _x.Tic.position.z, _x.Tic.orientation.x, _x.Tic.orientation.y, _x.Tic.orientation.z, _x.Tic.orientation.w, _x.Qwi.x, _x.Qwi.y, _x.Qwi.z, _x.Qwi.w, _x.gw.x, _x.gw.y, _x.gw.z, _x.VINSInitFlag.data, _x.TrackStatus.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Tic is None:
        self.Tic = geometry_msgs.msg.Pose()
      if self.Qwi is None:
        self.Qwi = geometry_msgs.msg.Quaternion()
      if self.gw is None:
        self.gw = geometry_msgs.msg.Point()
      if self.VINSInitFlag is None:
        self.VINSInitFlag = std_msgs.msg.Bool()
      if self.TrackStatus is None:
        self.TrackStatus = std_msgs.msg.Int8()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 114
      (_x.Tic.position.x, _x.Tic.position.y, _x.Tic.position.z, _x.Tic.orientation.x, _x.Tic.orientation.y, _x.Tic.orientation.z, _x.Tic.orientation.w, _x.Qwi.x, _x.Qwi.y, _x.Qwi.z, _x.Qwi.w, _x.gw.x, _x.gw.y, _x.gw.z, _x.VINSInitFlag.data, _x.TrackStatus.data,) = _struct_14dBb.unpack(str[start:end])
      self.VINSInitFlag.data = bool(self.VINSInitFlag.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      if python3:
        buff.write(struct.pack('<I%sB'%length, length, *_x))
      else:
        buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_14dBb.pack(_x.Tic.position.x, _x.Tic.position.y, _x.Tic.position.z, _x.Tic.orientation.x, _x.Tic.orientation.y, _x.Tic.orientation.z, _x.Tic.orientation.w, _x.Qwi.x, _x.Qwi.y, _x.Qwi.z, _x.Qwi.w, _x.gw.x, _x.gw.y, _x.gw.z, _x.VINSInitFlag.data, _x.TrackStatus.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.Tic is None:
        self.Tic = geometry_msgs.msg.Pose()
      if self.Qwi is None:
        self.Qwi = geometry_msgs.msg.Quaternion()
      if self.gw is None:
        self.gw = geometry_msgs.msg.Point()
      if self.VINSInitFlag is None:
        self.VINSInitFlag = std_msgs.msg.Bool()
      if self.TrackStatus is None:
        self.TrackStatus = std_msgs.msg.Int8()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 114
      (_x.Tic.position.x, _x.Tic.position.y, _x.Tic.position.z, _x.Tic.orientation.x, _x.Tic.orientation.y, _x.Tic.orientation.z, _x.Tic.orientation.w, _x.Qwi.x, _x.Qwi.y, _x.Qwi.z, _x.Qwi.w, _x.gw.x, _x.gw.y, _x.gw.z, _x.VINSInitFlag.data, _x.TrackStatus.data,) = _struct_14dBb.unpack(str[start:end])
      self.VINSInitFlag.data = bool(self.VINSInitFlag.data)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_14dBb = struct.Struct("<14dBb")
